import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  card: {
    padding: 24,
    borderRadius: 12,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14 } satisfies CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  headerActions: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 15,
    lineHeight: 1.6,
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  emptyTitle: { margin: "0 0 4px", fontSize: 15, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  muted: { fontSize: 14, color: "var(--text-secondary)", margin: "0 0 12px" } satisfies CSSProperties,
  note: (color: string): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 12,
    fontSize: 13,
    lineHeight: 1.45,
    color,
  }),
  noteIcon: { flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  missingList: { margin: "6px 0 0", paddingLeft: 18, fontSize: 12.5, color: "var(--warn)" } satisfies CSSProperties,
  link: { color: "var(--accent-text)", marginLeft: 6 } satisfies CSSProperties,
  /** Muted "where do specs come from" footer of the brief card. */
  hint: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 16,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  hintTitle: { fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  hintLinks: { display: "flex", flexWrap: "wrap", gap: 14, marginTop: 6 } satisfies CSSProperties,
  hintLink: { color: "var(--accent-text)", minHeight: 24, display: "inline-flex", alignItems: "center" } satisfies CSSProperties,
  twoCol: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: 16,
    alignItems: "start",
  } satisfies CSSProperties,
  focusList: { margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  /** File ref on top, the reason underneath at full row width. */
  focusRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
    width: "100%",
    minWidth: 0,
    textAlign: "left",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "transparent",
    padding: "8px 12px",
    fontSize: 13.5,
    color: "var(--text-primary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  focusRef: { color: "var(--accent-text)", fontSize: 12.5, maxWidth: "100%", overflowWrap: "anywhere" } satisfies CSSProperties,
  focusReason: { color: "var(--text-secondary)", lineHeight: 1.5, maxWidth: "100%", overflowWrap: "anywhere" } satisfies CSSProperties,
  skeletonStack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
} as const;
