import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 24 } satisfies CSSProperties,
  headerLeft: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  h2: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  versionChip: { border: "1px solid var(--border-strong)" } satisfies CSSProperties,
  enabledLabel: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  slugError: { fontSize: 12, color: "var(--crit)", marginTop: 8 } satisfies CSSProperties,
  trustNotice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 12.5,
    lineHeight: 1.45,
    marginBottom: 20,
  } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 24,
  } satisfies CSSProperties,
  actionButtons: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  snapshotHint: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.4 } satisfies CSSProperties,
  divider: { height: 1, background: "var(--border)", margin: "28px 0 20px" } satisfies CSSProperties,
  dangerZone: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
  } satisfies CSSProperties,
  dangerText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  dangerTitle: { fontSize: 13, fontWeight: 700, color: "var(--crit)", marginBottom: 6 } satisfies CSSProperties,
  dangerBody: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.45 } satisfies CSSProperties,
  deleteFooter: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
  deleteBody: { fontSize: 13.5, color: "var(--text-secondary)", lineHeight: 1.55 } satisfies CSSProperties,
} as const;
